plugins {
    id 'com.android.application'
}

android {
    namespace = 'com.legs.appsforaa.carify'
    compileSdk = 36

    defaultConfig {
        applicationId = 'com.legs.appsforaa.carify.bridgepayload'
        minSdk = 24
        targetSdk = 36
        versionCode = 1
        versionName = '1'
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.car.app:app:1.7.0'
    implementation 'androidx.car.app:app-projected:1.7.0'
}
